### ISSUE TITLE
input without centroids does not seem to work... 

### ISSUE THREAD

**Issue by mdesco** [scilus/tractometry_flow#5]
The pipeline only starts by renaming metrics and then completes. 
@arnaudbore  @frheault   can you help restore please.

Command used:
https://www.dropbox.com/s/t1rjfin8bx4njj3/cmd_marylie.sh?dl=0

Data used:
https://www.dropbox.com/s/z47hokvef4pctjg/input_data_tractometry.zip?dl=0

**Comment by arnaudbore** [comment]
I'm on it

**Comment by frheault** [comment]
There is a --use_provided_centroids, this is made to force the pipeline to use them.

This was made to avoid a naming convention error that was not being noticed because the pipeline was computing it by itself. This lead to people thinking they use the centroids from RBx when in fact it was computed subject-wise.

This was the intended behavior. This means you have a naming error (if you provided centroids and they are not being use)
